# Enable C++ support
language: cpp
compiler:
  - gcc
# Build steps
script:
  - mkdir build
  - cd build
  - qmake ../QProgramTV.pro -spec linux-g++ CONFIG+=qml_debug && /usr/bin/make qmake_all
  - make
