# Enable C++ support
language: cpp
compiler:
  - gcc
# Build steps
script:
  - mkdir build
  - cd build
  - qmake ../QProgramTV.pro -spec linux-g++ -std=c++11 CONFIG+=qml_debug && /usr/bin/make
  - make
